name = "school-timetable-frontend"
pages_build_output_dir = "dist"

[env.production]
compatibility_date = "2024-07-08"

[[env.production.env_vars]]
VITE_CLERK_PUBLISHABLE_KEY = "pk_test_ZXF1YWwteWV0aS00Ny5jbGVyay5hY2NvdW50cy5kZXYk"